### PR TITLE
Fix an issue for quote

### PR DESCRIPTION
**Pull request by Cokile**
1. Parser now can parse multiple paragraph correctly.

2. Change the style of quote so it is easy to  be distinguished from common
text.

### CODE REVIEW

**Comment by Cokile** [comment]
Here is the comparison for markdown text:
screen shot 2016-04-22 at 08 52 28


Before：
before


After：
after

**Comment by Coeur** [comment]
Thank you Cokile.

But requirements for TSMarkdownQuoteRegex is to have a space on third line of your example. If you want to make spaces optional, then you should use **TSMarkdownShortQuoteRegex**.

**Comment by Cokile** [comment]
@Coeur `TSMarkdownShortQuoteRegex` works for my example.

Anyway, only for your reference, you should use another font for quote text for a better user experience.

**Comment by Coeur** [comment]
Then revert the line that alters the regex and I will merge the font change :)

**Pull request merged**
