### PR TITLE
Update `Package.swift` to add `publicHeadersPath `, so headers can be found by Objective-C code when added via SPM.

### PR DESCRIPTION
**Pull request by vascoorey**
The current `Package.swift` definition is implicitly telling SPM that the headers are under the `include` folder (by omitting `publicHeaderPath`)

```
    /// The path to the directory that contains public headers of a C-family target.
    ///
    /// If this is `nil`, the directory is set to `include`.
    final public var publicHeadersPath: String?
```

This PR sets the `publicHeadersPath` to `.` so headers can be found by Objective-C code.

I have validated this fix and it appears that `#import <TSMarkdownParser.h>` now correctly finds the header.

### CODE REVIEW

**Comment by Coeur** [comment]
Link to that official doc: https://developer.apple.com/documentation/packagedescription/target/publicheaderspath

**Comment by Coeur** [comment]
Not knowing if there would be other side effects to moving those files for non-SPM adopters, can you instead try to replace:
```
            path: "TSMarkdownParser")
```
with:
```
            path: "TSMarkdownParser",
            publicHeadersPath: ".")
```
?

**Comment by vascoorey** [comment]
> Not knowing if there would be other side effects to moving those files for non-SPM adopters, can you instead try to replace:
> 
> ```
>             path: "TSMarkdownParser")
> ```
> 
> with:
> 
> ```
>             path: "TSMarkdownParser",
>             publicHeadersPath: ".")
> ```
> 
> ?

Good point mate, have applied you suggestion.

**Comment by Coeur** [comment]
Let me know when you have finished testing it.

**Review by Coeur — APPROVED** [review]

**Comment by vascoorey** [comment]
> Let me know when you have finished testing it.
> Oh, and kindly update the title of the PR accordingly, thanks.

Done and done, I've created a toy project with some objective-c files and they can find the headers correctly.

**Pull request merged**
